export { textVariants, textCva } from './ui/Text/config'
export { Text } from './ui/Text'
export type { TextProps } from './ui/Text'
export { Badge } from './ui/Badge'
export type { BadgeProps } from './ui/Badge'
