import { type DataByKey } from './types'

export const DATA: DataByKey = [
    {
        key: 'metadata.welcome.title',
        en: 'Welcome',
        ua: 'Ласкаво просимо',
        ru: 'Добро пожаловать',
    },
    {
        key: 'metadata.welcome.description',
        en: 'Welcome to our website',
        ua: 'Ласкаво просимо на наш веб-сайт',
        ru: 'Добро пожаловать на наш сайт',
    },
    {
        key: 'metadata.login.title',
        en: 'Log In',
        ua: 'Увійти',
        ru: 'Войти',
    },
    {
        key: 'metadata.login.description',
        en: 'Log In to your account',
        ua: 'Увійдіть до свого облікового запису',
        ru: 'Войдите в свою учетную запись',
    },
    {
        key: 'metadata.registration.title',
        en: 'Create Account',
        ua: 'Створити обліковий запис',
        ru: 'Создать учетную запись',
    },
    {
        key: 'metadata.registration.description',
        en: 'Create new account',
        ua: 'Створити новий обліковий запис',
        ru: 'Создать новую учетную запись',
    },
    {
        key: 'metadata.password_recovery.title',
        en: 'Password recovery',
        ua: 'Відновлення пароля',
        ru: 'Восстановление пароля',
    },
    {
        key: 'metadata.password_recovery.description',
        en: 'Recover your password',
        ua: 'Відновіть свій пароль',
        ru: 'Восстановите свой пароль',
    },
    {
        key: 'metadata.dashboard.title',
        en: 'Dashboard',
        ua: 'Панель управління',
        ru: 'Панель управления',
    },
    {
        key: 'metadata.dashboard.description',
        en: 'Access your dashboard',
        ua: 'Доступ до вашої панелі управління',
        ru: 'Доступ к вашей панели управления',
    },
    {
        key: 'metadata.admin-dashboard.title',
        en: 'Admin Dashboard',
        ua: 'Адміністраторська панель управління',
        ru: 'Административная панель управления',
    },
    {
        key: 'metadata.admin-dashboard.description',
        en: 'Access your admin dashboard',
        ua: 'Доступ до вашої адміністраторської панелі управління',
        ru: 'Доступ к вашей административной панели управления',
    },
    {
        key: 'metadata.forbidden.title',
        en: 'Forbidden',
        ua: 'Заборонено',
        ru: 'Запрещено',
    },
    {
        key: 'metadata.forbidden.description',
        en: 'You do not have permission to access this page.',
        ua: 'У вас немає доступу до цієї сторінки.',
        ru: 'У вас нет доступа к этой странице.',
    },
    {
        key: 'metadata.unauthorized.title',
        en: 'Unauthorized',
        ua: 'Неавторизований',
        ru: 'Неавторизованный',
    },
    {
        key: 'metadata.unauthorized.description',
        en: 'You are not authorized to access this page.',
        ua: 'Ви не авторизовані для доступу до цієї сторінки.',
        ru: 'Вы не авторизованы для доступа к этой странице.',
    },
    {
        key: 'global.welcome_to',
        en: 'Welcome to',
        ua: 'Ласкаво просимо до',
        ru: 'Добро пожаловать в',
    },
    {
        key: 'global.docs',
        en: 'Docs',
        ua: 'Документація',
        ru: 'Документация',
    },
    {
        key: 'global.access_documentation_to_get_started_and_master_vocabulary_trainer',
        en: 'Access documentation to get started and master Vocabulary Trainer.',
        ua: 'Отримайте доступ до документації, щоб почати та опанувати Vocabulary Trainer.',
        ru: 'Получите доступ к документации, чтобы начать и освоить Vocabulary Trainer.',
    },
    {
        key: 'global.login',
        en: 'Login',
        ua: 'Увійти',
        ru: 'Войти',
    },
    {
        key: 'global.sign_in_to_your_account_to_track_your_progress',
        en: 'Sign in to your account to track your progress.',
        ua: 'Увійдіть до свого облікового запису, щоб відстежувати свій прогрес.',
        ru: 'Войдите в свою учетную запись, чтобы отслеживать свой прогресс.',
    },
    {
        key: 'global.storybook',
        en: 'Storybook',
        ua: 'Сторібук',
        ru: 'Сторибук',
    },
    {
        key: 'global.explore_our_component_library_and_ui_design_system_for_vocabulary_trainer',
        en: 'Explore our component library and UI design system for Vocabulary Trainer.',
        ua: 'Досліджуйте нашу бібліотеку компонентів та систему дизайну UI для Vocabulary Trainer.',
        ru: 'Изучите нашу библиотеку компонентов и систему дизайна UI для Vocabulary Trainer.',
    },
    {
        key: 'global.dashboard',
        en: 'Dashboard',
        ua: 'Панель управління',
        ru: 'Панель управления',
    },
    {
        key: 'global.view_your_learning_statistics_set_goals_and_manage_your_vocabulary_lists',
        en: 'View your learning statistics, set goals, and manage your vocabulary lists.',
        ua: 'Перегляньте свою статистику навчання, встановіть цілі та керуйте своїми списками слів.',
        ru: 'Просмотрите свою статистику обучения, установите цели и управляйте своими списками слов.',
    },
    {
        key: 'global.theme',
        en: 'Theme',
        ua: 'Тема',
        ru: 'Тема',
    },
    {
        key: 'global.dark',
        en: 'Dark',
        ua: 'Темний',
        ru: 'Темный',
    },
    {
        key: 'global.light',
        en: 'Light',
        ua: 'Світлий',
        ru: 'Светлый',
    },
    {
        key: 'global.system',
        en: 'System',
        ua: 'Системний',
        ru: 'Системный',
    },
    {
        key: 'global.language',
        en: 'Language',
        ua: 'Мова',
        ru: 'Язык',
    },
    {
        key: 'global.english',
        en: 'English',
        ua: 'Англійська',
        ru: 'Английский',
    },
    {
        key: 'global.ukrainian',
        en: 'Ukrainian',
        ua: 'Українська',
        ru: 'Украинский',
    },
    {
        key: 'global.russian',
        en: 'Russian',
        ua: 'Російська',
        ru: 'Русский',
    },
    {
        key: 'global.unauthorized_access',
        en: 'Unauthorized Access',
        ua: 'Неавторизований доступ',
        ru: 'Неавторизованный доступ',
    },
    {
        key: 'global.forbidden_access',
        en: 'Forbidden Access',
        ua: 'Заборонений доступ',
        ru: 'Запрещенный доступ',
    },
    {
        key: 'global.you_do_not_have_permission_to_access_this_page',
        en: 'You do not have permission to access this page.',
        ua: 'У вас немає доступу до цієї сторінки.',
        ru: 'У вас нет доступа к этой странице.',
    },
    {
        key: 'global.access_denied',
        en: 'Access Denied',
        ua: 'Доступ заборонено',
        ru: 'Доступ запрещен',
    },
    {
        key: 'global.please_login_to_access_the_page',
        en: 'Please login to access the page',
        ua: 'Будь ласка, увійдіть до свого облікового запису, щоб отримати доступ до сторінки',
        ru: 'Пожалуйста, войдите в свою учетную запись, чтобы получить доступ к странице',
    },
    {
        key: 'global.insufficient_rights',
        en: 'Insufficient rights',
        ua: 'Недостатні права',
        ru: 'Недостаточно прав',
    },
    {
        key: 'global.go_to_login_page_to_login_and_get_access_to_the_page',
        en: 'Go to Login Page to login and get access to the page.',
        ua: 'Перейдіть на сторінку Вхід щоб зайти в свій аккаунт та отримати доступ до сторінки.',
        ru: 'Перейдите на страницу Входа что бы войти в свой аккаунт и получить доступ к странице.',
    },
    {
        key: 'global.please_contact_the_site_administrator_to_obtain_access_rights_to_this_page',
        en: 'Please contact the site administrator to obtain access rights to this page.',
        ua: 'Будь ласка, зверніться до адміністратора сайту, щоб отримати права доступу до цієї сторінки.',
        ru: 'Пожалуйста, свяжитесь с администратором сайта, чтобы получить права доступа к этой странице.',
    },
    {
        key: 'global.go_to_{pageName}_page',
        en: 'Go to {pageName} Page',
        ua: 'Перейти на сторінку {pageName}',
        ru: 'Перейти на страницу {pageName}',
    },
    {
        key: 'global.login_page_name',
        en: 'Login',
        ua: 'Вхід',
        ru: 'Входа',
    },
]
